#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPlatform.Dataverse.CodeSamples
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("searchsuggest")]
	public partial class searchsuggestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string entities
		{
			get
			{
				if (this.Parameters.Contains("entities"))
				{
					return ((string)(this.Parameters["entities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entities"] = value;
			}
		}
		
		public bool fuzzy
		{
			get
			{
				if (this.Parameters.Contains("fuzzy"))
				{
					return ((bool)(this.Parameters["fuzzy"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["fuzzy"] = value;
			}
		}
		
		public string filter
		{
			get
			{
				if (this.Parameters.Contains("filter"))
				{
					return ((string)(this.Parameters["filter"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["filter"] = value;
			}
		}
		
		public string orderby
		{
			get
			{
				if (this.Parameters.Contains("orderby"))
				{
					return ((string)(this.Parameters["orderby"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["orderby"] = value;
			}
		}
		
		public string options
		{
			get
			{
				if (this.Parameters.Contains("options"))
				{
					return ((string)(this.Parameters["options"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["options"] = value;
			}
		}
		
		public int top
		{
			get
			{
				if (this.Parameters.Contains("top"))
				{
					return ((int)(this.Parameters["top"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["top"] = value;
			}
		}
		
		public string search
		{
			get
			{
				if (this.Parameters.Contains("search"))
				{
					return ((string)(this.Parameters["search"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["search"] = value;
			}
		}
		
		public string propertybag
		{
			get
			{
				if (this.Parameters.Contains("propertybag"))
				{
					return ((string)(this.Parameters["propertybag"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["propertybag"] = value;
			}
		}
		
		public searchsuggestRequest()
		{
			this.RequestName = "searchsuggest";
			this.search = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("searchsuggest")]
	public partial class searchsuggestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public searchsuggestResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
