#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace MyApp.DataModel
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public partial class MyOrgContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public MyOrgContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MyApp.DataModel.ActivityParty"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MyApp.DataModel.ActivityParty> ActivityPartySet
		{
			get
			{
				return this.CreateQuery<MyApp.DataModel.ActivityParty>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MyApp.DataModel.Appointment"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MyApp.DataModel.Appointment> AppointmentSet
		{
			get
			{
				return this.CreateQuery<MyApp.DataModel.Appointment>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="MyApp.DataModel.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<MyApp.DataModel.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<MyApp.DataModel.SystemUser>();
			}
		}
	}
}
#pragma warning restore CS1591
