#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DataModel
{
	
	
	/// <summary>
	/// Power Pages Languages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum powerpagelanguages
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Arabic = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BasqueBasque = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulgarianBulgaria = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CatalanCatalan = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChineseChina = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChineseHongKongSAR = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChineseTraditional = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CroatianCroatia = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CzechCzechRepublic = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DanishDenmark = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DutchNetherlands = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		English = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EstonianEstonia = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FinnishFinland = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FrenchFrance = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GalicianSpain = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GermanGermany = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GreekGreece = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Hebrew = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HindiIndia = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HungarianHungary = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndonesianIndonesia = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ItalianItaly = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		JapaneseJapan = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KazakhKazakhstan = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KoreanKorea = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LatvianLatvia = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LithuanianLithuania = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MalayMalaysia = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Norwegian_BokmlNorway = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PolishPoland = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortugueseBrazil = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortuguesePortugal = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RomanianRomania = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RussianRussia = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Serbian_CyrillicSerbia = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Serbian_LatinSerbia = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SlovakSlovakia = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SlovenianSlovenia = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Spanish_TraditionalSortSpain = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SwedishSweden = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThaiThailand = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TurkishTrkiye = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UkrainianUkraine = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VietnameseVietnam = 1066,
	}
}
#pragma warning restore CS1591
