#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyApp.DataModel
{
	
	
	/// <summary>
	/// Value indicating whether security role is auto-assigned based on user license
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.11")]
	public enum securityrole_isautoassigned
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		No = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Yes = 1,
	}
}
#pragma warning restore CS1591
